block-list-secret-scan: []
download-external-modules: true
evaluate-variables: true
framework:
  - all
mask: []
output:
  - cli
  - sarif
  - github_failed_only
enable-secret-scan-all-files: true
secrets-scan-file-type: []
summary-position: top
quiet: true
soft-fail: false
compact: true
skip-check:
  # Want to use inputs on GitHub Actions
  - CKV_GHA_7
  # Ignore ALB errors for now
  - CKV_AWS_91
  - CKV_AWS_2
  - CKV_AWS_103
  # Not bothering with git hashes for now
  - CKV_TF_1
  # RETURN TO - ensuring SGs are attached to resources
  - CKV2_AWS_5
