block-list-secret-scan: []
download-external-modules: true
evaluate-variables: true
framework:
  - all
mask: []
output:
  - cli
  - sarif
  - github_failed_only
enable-secret-scan-all-files: true
secrets-scan-file-type: []
summary-position: top
quiet: true
soft-fail: false
compact: true
skip-check:
  # Want to use inputs on GitHub Actions
  - CKV_GHA_7
  # Ignore ALB errors for now
  - CKV_AWS_91
  - CKV_AWS_2
  - CKV_AWS_103
  # Not bothering with git hashes for now
  - CKV_TF_1
  # RETURN TO - ensuring SGs are attached to resources
  - CKV2_AWS_5
  # Not going to rotate secrets/keys currently
  - CKV2_AWS_57
  - CKV_AWS_7
  # TEMP - testing with Admin on Instance profile
  - CKV_AWS_274
  # Allow wildcards in policies
  - CKV_AWS_109
  - CKV_AWS_356
  # RDS Module - ignoring enahnced monitoring, performance insight, etc
  - CKV_AWS_118
  - CKV_AWS_293
  - CKV_AWS_353
  - CKV_AWS_157
  - CKV_AWS_338
  - CKV_AWS_304
  - CKV2_AWS_60
