name: Deploy Terraform Component
run-name: Running Terraform ${{ inputs.mode }} on Component ${{ inputs.component }} to Environment ${{ inputs.environment }}

concurrency:
  group: ${{ inputs.component }}-${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      component:
        description: Terraform Component to Deploy
        type: choice
        required: true
        options:
          - core
      environment:
        description: Environment to deploy into
        type: choice
        required: true
        default: acedev
        options:
          - acedev
      mode:
        description: Mode to run terraform in
        type: choice
        required: true
        default: plan
        options:
          - plan
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  runTerraform:
    name: Run Terraform
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_wrapper: false
          terraform_version: 1.7.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/DeploymentExecution
          role-session-name: DeploymentExecution
          role-duration-seconds: 3600

      - name: Terraform Plan
        id: tfplan
        run: |
          bin/terraform.sh --action ${{ inputs.mode }} \
            --project ${{ vars.PROJECT }} \
            --region ${{ vars.REGION }} \
            --component ${{ inputs.component }} \
            --environment ${{ vars.ENVIRONMENT }} \
            --group ${{ vars.GROUP }} \
            --build-id ${{ github.run_id }}

