name: Deploy Terraform Component
run-name: Running Terraform ${{ inputs.mode }} on Component ${{ inputs.component }} to Environment ${{ inputs.environment }}

concurrency:
  group: ${{ inputs.component }}-${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      component:
        description: Terraform Component to Deploy
        type: choice
        required: true
        options:
          - demo
      environment:
        description: Environment to deploy into
        type: choice
        required: true
        default: acedev
        options:
          - acedev
      mode:
        description: Mode to run terraform in
        type: choice
        required: true
        default: plan
        options:
          - plan
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  runTerraform:
    name: Run Terraform
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_wrapper: false
          terraform_version: 1.7.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/DeploymentExecution
          role-session-name: DeploymentExecution
          role-duration-seconds: 3600

      - name: Terraform Plan
        id: tfplan
        run: |
          ACTION=$(if [[ "${{ inputs.mode }}" == "destroy" ]]; then echo "plan-destroy"; else echo "plan"; fi)
          bin/terraform.sh --action "${ACTION}" \
            --project ${{ vars.PROJECT }} \
            --region ${{ vars.REGION }} \
            --component ${{ inputs.component }} \
            --environment ${{ vars.ENVIRONMENT }} \
            --group ${{ vars.GROUP }} \
            --build-id ${{ github.run_id }}

      - name: Generate TF Plan View
        id: tfplan-view
        run: |
          cd "components/${{ inputs.component }}"
          component=${{ inputs.component }}
          read component_name <<< "${component##*/}"
          if [ -f "build/${component_name}_${{ github.run_id }}.tfplan" ]; then
            echo "Getting plan for ${component_name}_${{ github.run_id }}.tfplan"
          else
            echo "ERROR: Build file not found"
            exit 1
          fi
          echo "### Terraform Plan" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          terraform show -no-color "build/${component_name}_${{ github.run_id }}.tfplan" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
